dbt_hdb_resale:
  outputs:
    dev:
      dataset: hdb_resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/aiml/.dbt/sctp-dsai-ds2-7eb2a1537443.json
      location: US
      method: service-account
      priority: interactive
      project: sctp-dsai-ds2
      threads: 1
      type: bigquery
  target: dev