version: 1
default_environment: dev
project_id: 0fd4461d-3eb3-4037-b2b8-f9d8d423b451
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      use_singer_decimal: true
      host: aws-0-us-east-2.pooler.supabase.com
      user: postgres.ufkutyufdohbogiqgjel
    select:
    - public-austin_bikeshare_trips.*
    - public-austin_bikeshare_stations.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      credentials_path: /Users/aiml/.dbt/sctp-dsai-ds2-7eb2a1537443.json
      dataset: austin_bike_elt
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: sctp-dsai-ds2
      location: US
      validate_records: true
