version: 2

sources:
  - name: 2austin_bikeshare_dagster_raw
    tables:
      - name: public_austin_bikeshare_stations
        meta:
          dagster:
            asset_key: ["meltano", "public_austin_bikeshare_stations"]

      - name: public_austin_bikeshare_trips
        meta:
          dagster:
            asset_key: ["meltano", "public_austin_bikeshare_trips"]

