version: 1
default_environment: dev
project_id: 67c41d52-bc2f-4c84-b264-892ffe076394
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-0-us-east-2.pooler.supabase.com
      use_singer_decimal: true
      user: postgres.ufkutyufdohbogiqgjel
    select:
    - public-austin_bikeshare_stations.*
    - public-austin_bikeshare_trips.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      credentials_path: /Users/aiml/.dbt/sctp-dsai-ds2-7eb2a1537443.json
      dataset: austin_bike_meltano_raw
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      location: US
      method: batch_job
      project: sctp-dsai-ds2
