dbt_austin_bikeshare:
  outputs:
    dev:
      dataset: austin_bikeshare_dagster
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/aiml/.dbt/sctp-dsai-ds2-7eb2a1537443.json # Use your path of key file
      location: US
      method: service-account
      priority: interactive
      project: sctp-dsai-ds2 # enter your google project id
      threads: 1
      type: bigquery
  target: dev