version: 1
default_environment: dev
project_id: 07a751e9-a0ad-4dc6-abdd-1c1a96fbd196
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-0-us-east-2.pooler.supabase.com
      user: postgres.ufkutyufdohbogiqgjel
    select:
    - public-austin_bikeshare_trips.*
    - public-austin_bikeshare_stations.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      credentials_path: /Users/aiml/.dbt/sctp-dsai-pt2-181ace543c96.json
      dataset: raw_austin_bikeshare_elt
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: sctp-dsai-pt2